/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Buscaminas.java
 *
 * Created on 18-may-2011, 10:56:19
 */
package programa;

import java.awt.Button;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author antoniosastre
 */
public class Buscaminas extends javax.swing.JFrame {

    







    /** Creates new form Buscaminas */
    public Buscaminas() {
        
        initComponents();
        selector.setSelectedItem("Fácil");
        desf.setMinimum(2);
        desf.setMaximum(30);
        desf.setValue(10);
        desc.setMinimum(2);
        desc.setMaximum(30);
        desc.setValue(10);
        desm.setMinimum(2);
        desm.setMaximum((desf.getValue() * desc.getValue()) - 2);
        desm.setValue(10);

        indf.setText("" + desf.getValue());
        indc.setText("" + desc.getValue());
        indm.setText("" + desm.getValue());


    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desf = new javax.swing.JSlider();
        desc = new javax.swing.JSlider();
        desm = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        selector = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        indf = new javax.swing.JTextField();
        indc = new javax.swing.JTextField();
        indm = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        botjugar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(725, 512));
        setResizable(false);

        desf.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                desfStateChanged(evt);
            }
        });

        desc.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                descStateChanged(evt);
            }
        });

        desm.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                desmStateChanged(evt);
            }
        });

        jLabel1.setText("Filas");

        jLabel2.setText("Columnas");

        jLabel3.setText("Minas");

        selector.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Fácil", "Medio", "Difícil", "Imposible", "Personalizado" }));
        selector.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                selectorItemStateChanged(evt);
            }
        });

        jLabel4.setText("Tableros Predefinidos");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        jLabel5.setText("Buscaminas 2.0");

        jLabel6.setText("Por Antonio Sastre");

        botjugar.setText("Jugar!");
        botjugar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botjugarMouseClicked(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jLabel5)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel6))
                    .add(layout.createSequentialGroup()
                        .add(128, 128, 128)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jLabel1)
                            .add(jLabel2)
                            .add(jLabel3))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(desm, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(desc, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(desf, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                            .add(layout.createSequentialGroup()
                                .add(jLabel4)
                                .add(14, 14, 14)
                                .add(selector, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(indf, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                            .add(indc, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                            .add(indm))))
                .addContainerGap(135, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(324, Short.MAX_VALUE)
                .add(botjugar)
                .add(325, 325, 325))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5)
                    .add(jLabel6))
                .add(85, 85, 85)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel4)
                            .add(selector, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(34, 34, 34)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jLabel1)
                            .add(desf, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(desc, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel2))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel3)
                            .add(desm, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(layout.createSequentialGroup()
                        .add(indf, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(indc, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(9, 9, 9)
                        .add(indm, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(46, 46, 46)
                .add(botjugar)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void descStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_descStateChanged
        int here2 = desm.getValue();
        desm.setMaximum((desf.getValue() * desc.getValue()) - 2);
        indc.setText("" + desc.getValue());
        desm.setValue(here2);
    }//GEN-LAST:event_descStateChanged

    private void desmStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_desmStateChanged
        desm.setMaximum((desf.getValue() * desc.getValue()) - 2);
        indm.setText("" + desm.getValue());
    }//GEN-LAST:event_desmStateChanged

    private void selectorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_selectorItemStateChanged
        switch (selector.getSelectedIndex()) {
            case 0:
                desf.setValue(10);
                desc.setValue(10);
                desm.setValue(10);

                break;

            case 1:

                desf.setValue(15);
                desc.setValue(15);
                desm.setValue(40);
                break;

            case 2:

                desf.setValue(15);
                desc.setValue(30);
                desm.setValue(100);
                break;

            case 3:

                desf.setValue(30);
                desc.setValue(30);
                desm.setValue(300);
                break;

            default:
                desf.setValue(desf.getMinimum());
                desc.setValue(desc.getMinimum());
                desm.setValue(desm.getMinimum());
                break;
        }
    }//GEN-LAST:event_selectorItemStateChanged

    private void botjugarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botjugarMouseClicked
        Juego juego = new Juego(desf.getValue(), desc.getValue(), desm.getValue());
        juego.setLocationRelativeTo(null);
		juego.setVisible(true);
        // Juego juego = new Juego(desf.getValue(), desc.getValue(), desm.getValue());


    }//GEN-LAST:event_botjugarMouseClicked

    public int getFilas(){
	    return desf.getValue();
    }
    public int getColumnas(){
	    return desc.getValue();
    }
    public int getMinas(){
	    return desm.getValue();
    }
    private void desfStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_desfStateChanged

        int here = desm.getValue();
        desm.setMaximum((desf.getValue() * desc.getValue()) - 2);
        indf.setText("" + desf.getValue());
        desm.setValue(here);
    }//GEN-LAST:event_desfStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Buscaminas().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botjugar;
    private javax.swing.JSlider desc;
    private javax.swing.JSlider desf;
    private javax.swing.JSlider desm;
    private javax.swing.JTextField indc;
    private javax.swing.JTextField indf;
    private javax.swing.JTextField indm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JComboBox selector;
    // End of variables declaration//GEN-END:variables
}
